### ISSUE TITLE
Common config.yaml structure for director and envoy.

### ISSUE THREAD

**Issue by dmitryagapov** [intel/openfl#382]
Director and envoy configs have different structures. For example:
```yaml
# director_config.yaml
settings: 
  listen_host: localhost
  listen_port: 50050
  sample_shape: [ '300', '400', '3' ]
  target_shape: [ '300', '400' ]
  envoy_health_check_period: 5  # in seconds

# envoy_config.yaml
params:
  cuda_devices: [0,2]
  
optional_plugin_components:
 cuda_device_monitor:
   template: openfl.plugins.processing_units_monitor.pynvml_monitor.PynvmlCUDADeviceMonitor
   settings: []

shard_descriptor:
  template: kvasir_shard_descriptor.KvasirShardDescriptor
  params:
    data_folder: kvasir_data
    rank_worldsize: 1,10
    enforce_image_hw: '300,400'
```
Looks like `settings` in `director_config.yaml` and `params` in `envoy_config.yaml` are used for the same porpose but have different names.
Would be great to have the same base param names in director and envoy configs.
